
.odbc_nanodbc_width <- function(x = NULL) {
  if (!is.null(x)) {
    variant <- attr(x, "nanodbc_width", exact = TRUE)
    if (!is.null(variant)) {
      return(variant)
    }
  }
  2L
}

.odbc_nanodbc_width_from_logical <- function(nanodbc_utf32) {
  if (isTRUE(nanodbc_utf32)) {
    4L
  } else {
    2L
  }
}

.odbc_call <- function(name, ..., variant_source = NULL) {
  width <- .odbc_nanodbc_width(variant_source)
  symbol <- if (identical(width, 4L)) paste0(name, "_utf32") else name
  .Call(symbol, ..., PACKAGE = "odbc")
}

.odbc_tag_variant <- function(x, nanodbc_utf32 = FALSE) {
  attr(x, "nanodbc_width") <- .odbc_nanodbc_width_from_logical(nanodbc_utf32)
  x
}
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

list_drivers_ <- function() {
    .odbc_call("_odbc_list_drivers_")
}

list_data_sources_ <- function() {
    .odbc_call("_odbc_list_data_sources_")
}

odbc_connect <- function(connection_string, timezone = "", timezone_out = "", encoding = "", name_encoding = "", bigint = 0L, timeout = 0L, r_attributes = NULL, interruptible_execution = TRUE, nanodbc_utf32 = FALSE) {
    variant_source <- structure(
        list(),
        nanodbc_width = .odbc_nanodbc_width_from_logical(nanodbc_utf32)
    )
    .odbc_tag_variant(
        .odbc_call(
            "_odbc_odbc_connect",
            connection_string,
            timezone,
            timezone_out,
            encoding,
            name_encoding,
            bigint,
            timeout,
            r_attributes,
            interruptible_execution,
            variant_source = variant_source
        ),
        nanodbc_utf32
    )
}

has_result <- function(p) {
    .odbc_call("_odbc_has_result", p, variant_source = p)
}

connection_info <- function(p) {
    .odbc_call("_odbc_connection_info", p, variant_source = p)
}

connection_quote <- function(p) {
    .odbc_call("_odbc_connection_quote", p, variant_source = p)
}

connection_release <- function(p) {
    invisible(.odbc_call("_odbc_connection_release", p, variant_source = p))
}

connection_begin <- function(p) {
    invisible(.odbc_call("_odbc_connection_begin", p, variant_source = p))
}

connection_commit <- function(p) {
    invisible(.odbc_call("_odbc_connection_commit", p, variant_source = p))
}

connection_rollback <- function(p) {
    invisible(.odbc_call("_odbc_connection_rollback", p, variant_source = p))
}

connection_valid <- function(p) {
    .odbc_call("_odbc_connection_valid", p, variant_source = p)
}

connection_sql_tables <- function(p, catalog_name = NULL, schema_name = NULL, table_name = NULL, table_type = NULL) {
    .odbc_call("_odbc_connection_sql_tables", p, catalog_name, schema_name, table_name, table_type, variant_source = p)
}

connection_sql_catalogs <- function(p) {
    .odbc_call("_odbc_connection_sql_catalogs", p, variant_source = p)
}

connection_sql_schemas <- function(p) {
    .odbc_call("_odbc_connection_sql_schemas", p, variant_source = p)
}

connection_sql_table_types <- function(p) {
    .odbc_call("_odbc_connection_sql_table_types", p, variant_source = p)
}

connection_sql_columns <- function(p, column_name = NULL, catalog_name = NULL, schema_name = NULL, table_name = NULL) {
    .odbc_call("_odbc_connection_sql_columns", p, column_name, catalog_name, schema_name, table_name, variant_source = p)
}

transactionLevels <- function() {
    .odbc_call("_odbc_transactionLevels")
}

set_transaction_isolation <- function(p, level) {
    invisible(.odbc_call("_odbc_set_transaction_isolation", p, level, variant_source = p))
}

bigint_mappings <- function() {
    .odbc_call("_odbc_bigint_mappings")
}

result_release <- function(r) {
    invisible(.odbc_call("_odbc_result_release", r, variant_source = r))
}

result_active <- function(r) {
    .odbc_call("_odbc_result_active", r, variant_source = r)
}

result_completed <- function(r) {
    .odbc_call("_odbc_result_completed", r, variant_source = r)
}

new_result <- function(p, sql, immediate) {
    .odbc_tag_variant(.odbc_call("_odbc_new_result", p, sql, immediate, variant_source = p))
}

result_fetch <- function(r, n_max = -1L) {
    .odbc_call("_odbc_result_fetch", r, n_max, variant_source = r)
}

result_column_info <- function(r) {
    .odbc_call("_odbc_result_column_info", r, variant_source = r)
}

result_bind <- function(r, params, batch_rows) {
    invisible(.odbc_call("_odbc_result_bind", r, params, batch_rows, variant_source = r))
}

result_insert_dataframe <- function(r, df, batch_rows) {
    invisible(.odbc_call("_odbc_result_insert_dataframe", r, df, batch_rows, variant_source = r))
}

result_describe_parameters <- function(r, df) {
    invisible(.odbc_call("_odbc_result_describe_parameters", r, df, variant_source = r))
}

result_rows_affected <- function(r) {
    .odbc_call("_odbc_result_rows_affected", r, variant_source = r)
}

result_row_count <- function(r) {
    .odbc_call("_odbc_result_row_count", r, variant_source = r)
}

column_types <- function(df) {
    invisible(.odbc_call("_odbc_column_types", df))
}
